UniversityManager/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManager.Models;

namespace UniversityManager.Controllers
{
    public class GroupController : Controller
    {
        private ApplicationDbContext _ctx;

        public GroupController()
        {
            _ctx = new ApplicationDbContext();
        }
        
        public ActionResult InfoUser()
        {
            return View();
        }
    }
}

UniversityManager/Controllers/UniversityController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManager.Models;

namespace UniversityManager.Controllers
{
    public class UniversityController : Controller
    {
       
     

        [Authorize(Roles = "Student")]
        public ActionResult StudentPanel()
        {
           
            return View();
        }

        [Authorize(Roles = "Teacher")]
        public ActionResult TeacherPanel()
        {

            return View();
        }
    }
}

UniversityManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @*<li>@Html.ActionLink("Groups", "Index", "Group")</li>*@
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin panel", "Dashboard", new { area = "Admin", controller = "AdminPanel" })</li>
                    }
                    @if (User.IsInRole("Teacher"))
                    {
                        <li>@Html.ActionLink("Teacher panel", "Dashboard", new { area = "Teacher", controller = "TeacherPanel" })</li>
                    }
                    @*@if (User.IsInRole("Admin"))
        {
            <li>@Html.ActionLink("Students", "StudentsList", "University")</li>
            <li>@Html.ActionLink("Teachers", "TeachersList", "University")</li>
        }*@
                    <li>@Html.ActionLink("Requests to group", "Index", "GroupRequest")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>